# syntax=docker/dockerfile:1
FROM php:8.1-fpm-alpine

# Environments
ENV TIMEZONE Europe/Warsaw

#install prereqs for extensions
RUN apk add --update --no-cache $PHPIZE_DEPS \
        git wget zsh zsh-vcs tzdata fzf fzf-zsh-completion openssh-client-default \
        libpq-dev icu-dev && \
        cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && \
        echo "${TIMEZONE}" > /etc/timezone

#install extensions
RUN docker-php-ext-install -j$(nproc) intl pdo_mysql pdo_pgsql sockets

#install PECL extensions
RUN pecl install xdebug apcu redis
RUN docker-php-ext-enable xdebug
RUN docker-php-ext-enable opcache
RUN docker-php-ext-enable redis

#fix www-data uid
RUN set -x \
    && deluser www-data \
    && addgroup -g 1000 -S www-data \
    && adduser -u 1000 -D -s /bin/bash -G www-data www-data

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

COPY ./php.ini /usr/local/etc/php/conf.d/custom-php.ini

USER www-data
WORKDIR /var/www